#services:
#  stats-server:
#    build: stats
#    image: stats_image
#    container_name: stats
#    ports:
#      - "9090:9090"
#    depends_on:
#      - stats-db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats
#      - SPRING_DATASOURCE_USERNAME=test
#      - SPRING_DATASOURCE_PASSWORD=test
#      - STATS_SERVER_URL=http://stats-server:9090
#
#  stats-db:
#    image: postgres:16.1
#    ports:
##      - "5432:5432"
#      - "5433:5432"
#    container_name: stats-postgres
#    environment:
#      - POSTGRES_PASSWORD=test
#      - POSTGRES_USER=test
#      - POSTGRES_DB=stats
#
##    healthcheck:
##      test: ["CMD-SHELL", "pg_isready -U stats"]
##      interval: 30s
##      timeout: 10s
##      retries: 5
#
#  ewm-service:
#    build: main-service
#    image: with_me_plus-ewm
#    container_name: with_me_plus-ewm
#    ports:
#      - "8080:8080"
#    depends_on:
#      - ewm-db
#      - stats-server
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm
#      - SPRING_DATASOURCE_USERNAME=ewm
#      - SPRING_DATASOURCE_PASSWORD=ewm
#
#  ewm-db:
#    image: postgres:16.1
#    ports:
##      - "5432:5432"
#     - "5434:5432"
#    container_name: ewm-postgres
#    environment:
#      - POSTGRES_PASSWORD=ewm
#      - POSTGRES_USER=ewm
#      - POSTGRES_DB=ewm
##    healthcheck:
##      test: ["CMD-SHELL", "pg_isready -U ewm"]
##      interval: 30s
##      timeout: 10s
##      retries: 5



services:
  stats-server:
    container_name: stats-server
    build: stats/stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-db:
    image: postgres:16.1
    container_name: postgres-stats-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build:
      context: main-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      main-db:
        condition: service_healthy
      stats-server:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5433/main-db
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345
      - STATS_SERVER_URL=http://stats-server:9090

  main-db:
    image: postgres:16.1
    container_name: postgres-main-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
