-- CREATE TABLE IF NOT EXISTS EndpointHit (
--                                            id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
--                                            app VARCHAR(512) NOT NULL,
--                                            uri VARCHAR(512) NOT NULL,
--                                            ip VARCHAR(512) NOT NULL,
--                                            timestamp TIMESTAMP
-- );
--
-- CREATE TABLE IF NOT EXISTS ViewStats (
--                                          app VARCHAR(512) NOT NULL,
--                                          uri VARCHAR(512) NOT NULL,
--                                          hits BIGINT
-- );
CREATE TABLE IF NOT EXISTS users (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     name VARCHAR(255) NOT NULL,
                                     email VARCHAR(512) NOT NULL,
                                     CONSTRAINT pk_user PRIMARY KEY (id),
                                     CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);