CREATE TABLE IF NOT EXISTS EndpointHit (
                                           id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                           app VARCHAR(512) NOT NULL,
                                           uri VARCHAR(512) NOT NULL,
                                           ip VARCHAR(512) NOT NULL,
                                           timestamp TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ViewStats (
                                         app VARCHAR(512) NOT NULL,
                                         uri VARCHAR(512) NOT NULL,
                                         hits BIGINT
);